name: build-release

on:
  push:
    tags:
    - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.1' # The Go version to download (if necessary) and use.
      # - name: Test
      #   run: ./test.sh
      - name: Build Linux
        run: |
          make
      - name: Package Linux
        run: |
          rm -rf package
          mkdir -p package/ssl-pairgen
          cp -a --parents README.md LICENSE ssl-pairgen kube-ca.sh bin/cfssl bin/cfssljson package/ssl-pairgen
          cd package
          tar czvf ../ssl-pairgen-linux.tar.gz ssl-pairgen
      - name: Clean Linux
        run: |
          make clean
      - name: Build Darwin
        run: |
          GOOS=darwin make
      - name: Package Darwin
        run: |
          rm -rf package
          mkdir -p package/ssl-pairgen
          cp -a --parents README.md LICENSE ssl-pairgen kube-ca.sh bin/cfssl bin/cfssljson package/ssl-pairgen
          cd package
          tar czvf ../ssl-pairgen-darwin.tar.gz ssl-pairgen
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        # softprops/action-gh-release v0.1.12
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb
        with:
          files: |
            ssl-pairgen-linux.tar.gz
            ssl-pairgen-darwin.tar.gz
